# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Cypress Report
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.16.0-chrome89-ff86
    steps:

      - uses: actions/checkout@v2

      - name: install cypress and verify it
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress Tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution screenshots
        run : |
          mkdir public
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report

      - name: Deploy report page to Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
